### ISSUE TITLE
reportportal_client.errors.ResponseError occurs when running tests

### ISSUE THREAD

**Issue by usr3514** [reportportal/agent-python-pytest#157]
Hi All, 

When i run the tests with --reportportal the tests run successfully but at the end it throws the error '_reportportal_client.errors.ResponseError: TestItem with ID = '2be489f2-b762-4f36-8195-092044f6feb6' successfully finished._'.  

Also the **reportportal launch hangs** 
![report-portal hangs](https://user-images.githubusercontent.com/39473789/72819990-362d8280-3c94-11ea-9107-720f86817238.png)

```
Tests run:
import time

def test_one():
    print('test_one')
    time.sleep(5)

def test_two():
    print('test_two')
    time.sleep(5)
```

```
platform win32 -- Python 3.7.5, pytest-5.3.0, py-1.8.0, pluggy-0.13.0
sensitiveurl: .*
rootdir: C:\Sprint\longhorn\scratch, inifile: pytest.ini
plugins: allure-pytest-2.6.2, base-url-1.4.1, forked-1.1.3, html-1.15.2, metadata-1.8.0, reportportal-1.0.9, rerunfailures-8.0, selenium-1.16.0, slack-2.0.0, variables-1.5.0, xdist-1.29.0
collected 2 items                                                                                                                

test_test_one.py ..                                                                                                        [100%]Traceback (most recent call last):
  File "c:\users\usr\envs\dev_auto_375\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\users\usr\envs\dev_auto_375\lib\site-packages\reportportal_client\service.py", line 231, in finish_test_item
    return _get_msg(r)
  File "c:\users\usr\envs\dev_auto_375\lib\site-packages\reportportal_client\service.py", line 40, in _get_msg
    return _get_data(response)["msg"]
  File "c:\users\usr\envs\dev_auto_375\lib\site-packages\reportportal_client\service.py", line 52, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: TestItem with ID = '2be489f2-b762-4f36-8195-092044f6feb6' successfully finished.


!!!!!!!!!!!! _pytest.outcomes.Exit: TestItem with ID = '2be489f2-b762-4f36-8195-092044f6feb6' successfully finished. !!!!!!!!!!!!
================================================= 2 passed in 60.34s (0:01:00) ==================================================
```

**Comment by iivanou** [comment]
@usr3514 What is the version of the Report Portal you are trying to report to?

**Comment by MikeFez** [comment]
I am also experiencing this issue after upgrading to Report Portal v5.

**Comment by iivanou** [comment]
Currently, Python agents do not support Report Portal v. 5. A new version of the agent will be released for version 5 and higher.

**Comment by usr3514** [comment]
@iivanou  Thank you for the info. Even i'm using version v.5

**Comment by iivanou** [comment]
Closed as the agent for RPv5 has been released.
