### ISSUE TITLE
Reportportal Pytest Plugin Causes Pytest to Fail with an Internal Error with Pytest version 5.4.0

### ISSUE THREAD

**Issue by subecho** [reportportal/agent-python-pytest#165]
In my CI environment, where Pytest is being run in a container (specifically the Python 3.8 docker image) it appears that it is looking for an attribute that no longer exists in `_pytest.logging`. This seems to have occurred before any sort of test collection or execution.

**Operating System**: Docker Image for Python 3.8
**Pytest Version**: 5.4.0
**pytest-reportportal Version**: 1.10.0

```
 INTERNALERROR> Traceback (most recent call last):
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/_pytest/main.py", line 187, in wrap_session
 INTERNALERROR>     config._do_configure()
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
 INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
 INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
 INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
 INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
 INTERNALERROR>     return outcome.get_result()
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
 INTERNALERROR>     raise ex[1].with_traceback(ex[2])
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
 INTERNALERROR>     res = hook_impl.function(*args)
 INTERNALERROR>   File "/path/to/.venv/lib/python3.8/site-packages/pytest_reportportal/plugin.py", line 160, in pytest_configure
 INTERNALERROR>     log_level = _pytest.logging.get_actual_log_level(config, 'rp_log_level')
 INTERNALERROR> AttributeError: module '_pytest.logging' has no attribute 'get_actual_log_level'
```
Please let me know if I can help or if you need additional information.

**Comment by iivanou** [comment]
Unfortunately, contributors of the Pytest can change names of the functions as they want, even without deprecation period: #https://github.com/pytest-dev/pytest/pull/6849.

**Comment by subecho** [comment]
> Unfortunately, contributors of the Pytest can change names of the functions as they want, even without deprecation period: #[pytest-dev/pytest#6849](https://github.com/pytest-dev/pytest/pull/6849).

That's...unfortunate. Fortunately, it looks like your patch fixes the issue I was seeing and I was able to get the tests to run and report successfully with the `v1` branch against pytest `5.4.1`. Thank you, @iivanou!
