### ISSUE TITLE
Feature request: Link issues to test case from python code

### ISSUE THREAD

**Issue by AnatoliiSliusarievSecurrency** [reportportal/agent-python-pytest#167]
Could you, please, add ability to link issues to test cases from python code? Currently I'm using Jira and want to have ability to add markers maybe something like this:
`@pytest.mark.issue(id="CASE-011")`
so that when I run it in reportportal, it will link my issue to Jira automatically.

If it's not implemented of course yet, but I've asked in reportportal slack and they sent me here:)

**Comment by iivanou** [comment]
@AnatoliiSliusarievSecurrency, you can achieve your goal using the following options in the .ini file:

rp_issue_marks = 'xfail' 'issue' - Pytest marks that could be used to get issue information (id, type, reason)
rp_issue_system_url = http://bugzilla.some.com/show_bug.cgi?id={%issue_id} - issue URL (issue_id will be filled by parameter from pytest mark)
rp_issue_id_marks = True - Enables adding marks for issue ids (e.g. "issue:123456")


[How to](https://github.com/reportportal/agent-python-pytest#test-issue-info)

**Comment by AnatoliiSliusarievSecurrency** [comment]
when I do that I get KeyError: "%issue_id"

in my pytest.ini I have:
rp_issue_id_marks = True
rp_issue_marks = 'xfail' 'issue'
rp_issue_system_url = http://jira.link.com/projects/PROJECT/issues/{%issue_id}

in my test case I have marker:
@pytest.mark.issue(issue_id='ABC-8116', reason='some_bug', issue_type='DB')

but when I do that I get KeyError: "%issue_id"

**Comment by iivanou** [comment]
I need a full stack trace...

**Comment by AnatoliiSliusarievSecurrency** [comment]
platform darwin -- Python 3.7.7, pytest-3.8.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/USER/Coding/API-Tests, inifile: pytest.ini
plugins: reportportal-5.0.0, dependency-0.4.0, allure-pytest-2.5.4
collected 1 item                                                                                                                                                                        

automation_tests/tests/hello_test.py 
17/03/2020 13:23:47 PM ReportPortal - Finish TestItem: request_body={'end_time': '1584437027024', 'status': 'PASSED', 'issue': None, 'item_id': '7d5773d6-93cc-4c8d-9d01-0bcbd9edbea9'} 

17/03/2020 13:23:47 PM ReportPortal - End TestSuite: request_body={'end_time': '1584437027025', 'issue': None, 'item_id': 'eac6d8fe-7b5f-4082-a6dd-624f6772573e', 'status': 'PASSED'} 

17/03/2020 13:23:47 PM http://52.226.36.64:8080 "PUT /api/v2/superadmin_personal/item/eac6d8fe-7b5f-4082-a6dd-624f6772573e HTTP/1.1" 200 93 

17/03/2020 13:23:47 PM finish_test_item - ID: eac6d8fe-7b5f-4082-a6dd-624f6772573e 

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 215, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 236, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/runner.py", line 163, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 84, in pytest_runtest_makereport
INTERNALERROR>     self._add_issue_info(item, report)
INTERNALERROR>   File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 133, in _add_issue_info
INTERNALERROR>     issue_url = mark_url.format(issue_id=issue_id) if mark_url else None
INTERNALERROR> KeyError: '%issue_id'
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/capture.py", line 406, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/USER/Coding/API-Tests/venv_auto/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/config/__init__.py", line 67, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 201, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/plugin.py", line 112, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "/Users/USER/Coding/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/service.py", line 312, in finish_launch
    log.debug('ReportPortal - Finish launch: request_body=%s', fl_rq)
Message: 'ReportPortal - Finish launch: request_body=%s'
Arguments: {'end_time': '1584437027333', 'status': None}
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/capture.py", line 406, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/API-Tests/venv_auto/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/config/__init__.py", line 67, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 201, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/plugin.py", line 112, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/service.py", line 313, in finish_launch
    self.rp.finish_launch(**fl_rq)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/reportportal_client/service.py", line 187, in finish_launch
    r = self.session.put(url=url, json=data, verify=self.verify_ssl)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/urllib3/connectionpool.py", line 393, in _make_request
    httplib_response.length)
Message: '%s://%s:%s "%s %s %s" %s %s'
Arguments: ('http', '52.226.36.64', 8080, 'PUT', '/api/v1/superadmin_personal/launch/e4a41089-8a21-44d8-8f01-314dc638da9b/finish', 'HTTP/1.1', 200, 131)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/capture.py", line 406, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/API-Tests/venv_auto/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/config/__init__.py", line 67, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 201, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/plugin.py", line 112, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/service.py", line 313, in finish_launch
    self.rp.finish_launch(**fl_rq)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/reportportal_client/service.py", line 188, in finish_launch
    logger.debug("finish_launch - ID: %s", self.launch_id)
Message: 'finish_launch - ID: %s'
Arguments: ('e4a41089-8a21-44d8-8f01-314dc638da9b',)

============================================================================= no tests ran in 1.29 seconds ==============================================================================
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/capture.py", line 406, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/API-Tests/venv_auto/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/config/__init__.py", line 67, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/main.py", line 203, in wrap_session
    config._ensure_unconfigure()
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/_pytest/config/__init__.py", line 607, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/API-Tests/venv_auto/lib/python3.7/site-packages/pytest_reportportal/plugin.py", line 183, in pytest_unconfigure
    log.debug('RP is unconfigured')
Message: 'RP is unconfigured'
Arguments: ()

**Comment by iivanou** [comment]
Remove '%' symbol from the value of your rp_issue_system_url parameter:

'http://jira.link.com/projects/PROJECT/issues/{issue_id}'

**Comment by AnatoliiSliusarievSecurrency** [comment]
I don't see any errors now, but issue is not linked in reportportal...

**Comment by iivanou** [comment]
Two questions:

1. Why do you think that the issue is not linked?
2. I need to see the logs from the execution that include reportportal_client logs.

**Comment by iivanou** [comment]
Currently, we do not support linking issues from BTS. We support just adding an issues to test results. Leave this as a feature request. I have just fixed adding issues in #168 .

**Comment by HardNorth** [comment]
@AnatoliiSliusarievSecurrency It's not possible to use `DB` issue type unless you register it in your project. E.G. here: http://localhost:8080/ui/#default_personal/settings/defect
Everything else works as expected for now. I added special example to demonstrate the feature: https://github.com/reportportal/examples-python/blob/master/pytest/tests/test_issue_id.py

I also moved feature logic update to different issue, since it's necessary to change feature behavior: #289
