### ISSUE TITLE
Plugin crash due to bad request with invalid CPU value by default

### ISSUE THREAD

**Issue by mahan21** [reportportal/agent-python-pytest#190]
I'm running with the example config from the read me and the plugin is crashing with the follow trace. It seems like an attribute value is empty.

```
PYTHONPATH=:/home/user/proj/backend-auth py.test --reportportal -c tests/conf/pytest.ini tests/functional
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/_pytest/main.py", line 189, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pytest_reportportal/plugin.py", line 63, in pytest_sessionstart
INTERNALERROR>     session.config.py_test_service.start_launch(
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/pytest_reportportal/service.py", line 161, in start_launch
INTERNALERROR>     item_id = self.rp.start_launch(**sl_pt)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 221, in start_launch
INTERNALERROR>     self.launch_id = _get_id(r)
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 66, in _get_id
INTERNALERROR>     return _get_data(response)["id"]
INTERNALERROR>   File "/home/user/proj/backend-auth/venv/lib/python3.8/site-packages/reportportal_client/service.py", line 98, in _get_data
INTERNALERROR>     raise ResponseError(error_messages[0])
INTERNALERROR> reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.]
make: *** [Makefile:14: ft] Error 3
```

When looking at the actual request in Wireshark. It seems like the value for CPU is empty and that the receiver isn't too happy about that. Other things to mention is the agent value that seems a bit strange. Overall I can't see any attempts to transfer actual tests results, do I need further configuration?

```
POST /v2/systemx/launch HTTP/1.1
Host: localhost:8080
User-Agent: python-requests/2.23.0
Content-Length: 377
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: bearer abf7e499-29a2-44f5-b34c-a78c928a8fba
Content-Type: application/json
X-Forwarded-For: 172.20.0.1
X-Forwarded-Host: localhost:8080
X-Forwarded-Port: 8080
X-Forwarded-Prefix: /api
X-Forwarded-Proto: http
X-Forwarded-Server: 6aca1dff8075
X-Real-Ip: 172.20.0.1

{"name": "AuthBackend", "description": "'Functional tests for AuthBackend'", "attributes": [{"key": "agent", "value": "pytest-reportportal-pytest-reportportal 5.0.2", "system": true}, {"key": "cpu", "value": "", "system": true}, {"key": "machine", "value": "x86_64", "system": true}, {"key": "os", "value": "Linux", "system": true}], "startTime": "1586944004116", "mode": null}
```

**Comment by mahan21** [comment]
This bug is solved by the following patch in the python client:
https://github.com/reportportal/client-Python/commit/cb661c5319dfd0343bf4734c64ff7d1e4dd8ccf0
