### ISSUE TITLE
error sending results to the portal

### ISSUE THREAD

**Issue by ainur-fa** [reportportal/agent-python-pytest#192]
pytest-reportportal 5.0.3 + reportpportal 5.1.0
the situation is this: the same tests are running on 4 virtual machines (a different test environment and each machine adds information about its test environment to the attributes)
stably on one of them I get an error:

```
finish_launch - ID: b33efba2-2734-4fb7-b061-7e8981ce9e57

RP is unconfigured
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 233, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 226, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.6/site-packages/_pytest/terminal.py", line 681, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/pytest_reportportal/plugin.py", line 96, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "/usr/lib/python3.6/site-packages/pytest_reportportal/service.py", line 310, in finish_launch
    self.rp.finish_launch(**fl_rq)
  File "/usr/lib/python3.6/site-packages/reportportal_client/service.py", line 241, in finish_launch
    return _get_msg(r)
  File "/usr/lib/python3.6/site-packages/reportportal_client/service.py", line 80, in _get_msg
    return _get_data(response)
  File "/usr/lib/python3.6/site-packages/reportportal_client/service.py", line 98, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 5000: Unclassified error [could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement]
```

while the tests themselves pass successfully.
sometimes I get this:

```
finish_launch - ID: 253bea34-f26c-41fa-a88f-10f6a59d72bd

RP is unconfigured
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 233, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 226, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/site-packages/_pytest/terminal.py", line 681, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/plugin.py", line 96, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/service.py", line 310, in finish_launch
    self.rp.finish_launch(**fl_rq)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 241, in finish_launch
    return _get_msg(r)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 80, in _get_msg
    return _get_data(response)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 98, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 4041: Launch '253bea34-f26c-41fa-a88f-10f6a59d72bd' not found. Did you use correct Launch ID?
```

**Comment by iivanou** [comment]
Could you please elaborate on this "each machine adds information about its test environment to the attributes"? How exactly do you start your tests?

**Comment by ainur-fa** [comment]
I have a crutch that before the tests creates a pytest.ini with the necessary fields, there are no hooks or changes in the pytest-reportportal code.

**Comment by iivanou** [comment]
The root cause is not obvious seeing at the given information. I'll need more information, debug logs, and something that can be reproduced.

**Comment by ainur-fa** [comment]
can you write from where (from the server or from the client) which logs and how to get them?

**Comment by iivanou** [comment]
I need Pytest debug logs. Run pytest with option --log-cli-level=DEBUG,

**Comment by ainur-fa** [comment]
[log.txt](https://github.com/reportportal/agent-python-pytest/files/4516085/log.txt)

**Comment by iivanou** [comment]
Can you try to report your tests to https://beta.demo.reportportal.io/ui/? Let's make sure your RP instance is correctly installed.

**Comment by ainur-fa** [comment]
report sent to the  https://beta.demo.reportportal.io  successfully!
https://beta.demo.reportportal.io/ui/#ainur-fa_personal/launches/all
apparently something is wrong with the server ....

**Comment by iivanou** [comment]
Do you mind closing this issue?

**Comment by ainur-fa** [comment]
Thanks, close.
