### ISSUE TITLE
[help required] ModuleNotFoundError: No module named 'six.moves.collections_abc'

### ISSUE THREAD

**Issue by vishallanke** [reportportal/agent-python-pytest#237]
I can see that 'six' module inside site_packages

```
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages>pip install six
Requirement already satisfied: six in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages (1.12.0)
```

```
**[ ERROR ] Taking listener 'robotframework_reportportal.listener' into use failed: Importing listener 'robotframework_reportportal.listener' failed: ModuleNotFoundError: No module named 'six.moves.collections_abc'
Traceback (most recent call last):**
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\robotframework_reportportal\listener.py", line 3, in <module>
    from reportportal_client.helpers import gen_attributes
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\reportportal_client\__init__.py", line 17, in <module>
    from .service import ReportPortalService
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\reportportal_client\service.py", line 25, in <module>
    from six.moves.collections_abc import Mapping
**PYTHONPATH:
  C:\Users\admin\AppData\Local\Programs\Python\Python37-32\Scripts\robot.exe
  c:\users\admin\appdata\local\programs\python\python37-32\python37.zip
  c:\users\admin\appdata\local\programs\python\python37-32\DLLs
  c:\users\admin\appdata\local\programs\python\python37-32\lib
  c:\users\admin\appdata\local\programs\python\python37-32
  c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages**
```

**Comment by vishallanke** [comment]
None of the options worked
Finally issue is reoslved after doing below

`pip install --ignore-installed six
`
