### ISSUE TITLE
Not-started service termination for wrong uuid.

### ISSUE THREAD

**Issue by krasoffski** [reportportal/agent-python-pytest#24]
Need to check with more options.

__How to reproduce:__
1. Create `pytest.ini` file and specify invalid `rp_uuid` parameter and `rp_ignore_errors = True`.
2. Copy paste example from readme file to test_sample.py
3. Run tests with command: `pytest test_sample.py`

__Actual result for launch with all passed tests__:
Traceback about service terminating is printed out but should not.
```
$ pytest test_sample.py 
============================================================ test session starts =============================================================
platform linux2 -- Python 2.7.12, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: /home/ykrasouski/ReportPortal, inifile: pytest.ini
plugins: reportportal-1.0.0
collected 1 items 

test_sample.py .

========================================================== 1 passed in 0.01 seconds ==========================================================
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 73, in _monitor
    self.handle(record)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 54, in handle
    handler(record)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 208, in process_item
    self.terminate(nowait=True)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
Error: Service already stopped.

```
__Actual result for launch with failed tests__:
In some cases output mixed up due to thread like bellow:
```
$ pytest test_sample.py 
============================================================ test session starts =============================================================
platform linux2 -- Python 2.7.12, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: /home/ykrasouski/ReportPortal, inifile: pytest.ini
plugins: reportportal-1.0.0
collected 1 items 

test_sample.py FTraceback (most recent call last):
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service.py", line 126, in start_launch
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 73, in _monitor
    self.handle(record)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 54, in handle
    handler(record)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 208, in process_item
    self.terminate(nowait=True)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
Error: Service already stopped.

    self.launch_id = _get_id(r)
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service.py", line 14, in _get_id
    return _get_data(response)["id"]
  File "/home/ykrasouski/ReportPortal/client-python/reportportal_client/service.py", line 39, in _get_data
    response.raise_for_status()
  File "/home/ykrasouski/.virtualenvs/rp/local/lib/python2.7/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error:  for url: https://rp/api/v1/project/launch


================================================================== FAILURES ==================================================================
__________________________________________________________________ test_one __________________________________________________________________

    def test_one():
        logger.info("Case1. Step1")
        x = "this"
        logger.info("x is: %s", x)
>       assert 'x' in x
E       AssertionError: assert 'x' in 'this'

test_sample.py:20: AssertionError
------------------------------------------------------------ Captured stderr call ------------------------------------------------------------
INFO:test_sample:Case1. Step1
INFO:test_sample:x is: this
========================================================== 1 failed in 0.03 seconds ==========================================================
```

**Comment by DKorytkin** [comment]
When you make fix this bug?

**Comment by krasoffski** [comment]
Hi,
It is hard to say because RP Python part is developed by community using their personal free time, thus it is hard to predict.
P.S. Any help/contribution from your side is very appreciated.

**Comment by krasoffski** [comment]
I'm started investigation of this issue.
The root cause of problem is following part of code 
```
def terminate_service(self):
    if self.RP is not None:
        self.RP.terminate()
```
`self.RP` is instance of `ReportPortalServiceAsync` which contains instance of `ReportPortalService` and as a result quite rare can be `None`.

**Comment by avarabyeu** [comment]
@krasoffski can we close it?

**Comment by krasoffski** [comment]
I think, the issue is still valid and root cause is plug-in architecture (if there is no significant changes in the code past few months).
But as an option we can close and wait till first user comments here :-)

**Comment by avarabyeu** [comment]
so maybe we can just fix it?) does it require significant changes?

**Comment by DzmitryHumianiuk** [comment]
@krasoffski what is the result for this issue?

**Comment by krasoffski** [comment]
Need to check, but I think this issue is still valid.
