### ISSUE TITLE
requests.exceptions.JSONDecodeError in pytest-reportportal v5.2.1 

### ISSUE THREAD

**Issue by manvendravsingh** [reportportal/agent-python-pytest#348]
I have update the python-reportportal to latest build. and now I am facing following issue-

PS C:\Users*****\PycharmProjects\MyProject> pytest --reportportal

---------------------------- live log sessionstart ----------------------------
rp_requests.py 83 WARNING Report Portal None request failed
Traceback (most recent call last):
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
timeout=self.http_timeout)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in init
self._data = self.get_json(data)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json
return data.json()
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
rp_requests.py 83 WARNING Report Portal None request failed
Traceback (most recent call last):
File "C:\Users*****\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, kwargs)
File "C:\Users****\AppData\Local\Programs\Python\Python37\lib\json_init.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
timeout=self.http_timeout)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in init
self._data = self._get_json(data)
File "C:\Users*\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json
return data.json()
File "C:\Users*****\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.10.1, py-1.11.0, pluggy-1.0.0 -- C:\Users*\AppData\Local\Programs\Python\Python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.0', 'Platform': 'Windows-10-10.0.19041-SP0', 'Packages': {'pytest': '3.10.1', 'pluggy': '1.0.0'}, 'Plugins': {'depends': '1.0.1', 'html': '1.22.0', 'metadata'
: '2.0.4', 'reportportal': '5.2.1'}}
rootdir: C:\Users******\PycharmProjects\MyProject, inifile: pytest.ini
plugins: depends-1.0.1, html-1.22.0, metadata-2.0.4, reportportal-5.2.1
collected 2 items

----------------------------- live log collection -----------------------------
rp_requests.py 83 WARNING Report Portal None request failed
Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
timeout=self.http_timeout)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in init
self._data = self._get_json(data)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json
return data.json()
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

test_sample.py::TestSample::test_sampleTest1
------------------------------- live log setup --------------------------------
conftest.py 18 INFO Test Started
-------------------------------- live log call --------------------------------
test_sample.py 10 INFO This is Sample Test 1
PASSED [ 50%]
------------------------------- live log finish -------------------------------
client.py 248 WARNING Attempt to finish non-existent item
rp_requests.py 83 WARNING Report Portal None request failed
Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
timeout=self.http_timeout)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in init
self._data = self._get_json(data)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json
return data.json()
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

test_sample.py::TestSample::test_sampleTest2
-------------------------------- live log call --------------------------------
test_sample.py 14 INFO This is sample Test 2
PASSED [100%]
------------------------------ live log teardown ------------------------------
conftest.py 20 INFO Test End
------------------------------- live log finish -------------------------------
client.py 248 WARNING Attempt to finish non-existent item
--------------------------- live log sessionfinish ----------------------------
client.py 205 WARNING Attempt to finish non-existent launch
rp_requests.py 83 WARNING Report Portal None request failed
Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
timeout=self.http_timeout)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in init
self._data = self._get_json(data)
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json
return data.json()
File "C:\Users\masing\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

========================== 2 passed in 1.38 seconds ===========================

I am using Python version 3.7.0. Please help.

**Comment by HardNorth** [comment]
@manvendravsingh that means your server didn't response with a JSON. Could you please describe how you configure your agent?

**Comment by manvendravsingh** [comment]
I am using demo report portal. I have update my pytest.ini with following settings. 
rp_endpoint = https://demo.reportportal.io/asd
rp_api_key = ******************************************************
rp_project = default_personal
rp_launch = *********************

Then as suggested in [readme](https://github.com/reportportal/agent-python-pytest)  I have created rp_logger - 
from reportportal_client import RPLogger

@pytest.fixture(scope="session")
def rp_logger():
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    logging.setLoggerClass(RPLogger)
    return logger

and using this logger in my pytest Tests. as - 
@pytest.mark.usefixtures("setup")   # Setup is just someother fixture printing Hi as of now. 
class TestSample:

    def test_sampleTest1(self,rp_logger):
        rp_logger.info("This is Sample Test 1")
        assert True

now I am executing the test cases using command - pytest --reportportal

Please let me know if I am missing something.

**Comment by rplevka** [comment]
```
rp_endpoint = https://demo.reportportal.io/asd
```
remove the `/asd`.

**Comment by manvendravsingh** [comment]
Thanks for reply. I am able to send test results on demo site now. 

Now, I have applied same changes in live project and I am facing the same issue. The main difference is that, In my live project has reportportal is deployed our port 8080 so I have to use the rp_endpoint= http://myliveprojectsite.com:8080. 
But when I doing this I am facing the same JsonDecodeError. 
12:29:57 - [reportportal_client.core.rp_requests] - WARNING: Report Portal None request failed
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_requests.py", line 76, in make
    timeout=self.http_timeout)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 64, in __init__        
    self._data = self._get_json(data)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\site-packages\reportportal_client\core\rp_responses.py", line 74, in _get_json       
    return data.json()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have tried to connect without giving the port then server is refusing the connection. (as expected)

It seems like while parsing the port in endpoint JsonDecoder is failing. Please help .

**Comment by HardNorth** [comment]
@manvendravsingh When I test the agent locally I also use port 8080 and that's cause no issue. So I would check that your instance actually working.

**Comment by manvendravsingh** [comment]
My instance is reachable. It is working fine with Python-reportportal 1.0.2 . I am trying to update to new version. Is it required to update the instance also ?

**Comment by HardNorth** [comment]
@manvendravsingh So you are using custom solution, that explains a lot. I believe you need to double-check your URLs, there's no any different reason to get such error, except invalid URL (on working instance). Even incorrect credentials return JSON response.

**Comment by rplevka** [comment]
@manvendravsingh you can place a breakpoint [here](https://github.com/reportportal/client-Python/blob/develop/reportportal_client/core/rp_responses.py#L74) and see what is inside the response (`data.text`).
That will give you a hint.
@HardNorth, we might wrap that inside a try-except block and append the text of the response in the Error to help users to figure out what is going on (in the future)
