### ISSUE TITLE
AttributeError: 'MarkMapping' object has no attribute '_mymarks'

### ISSUE THREAD

**Issue by akhmialevskiy** [reportportal/agent-python-pytest#37]
For both Python2 and Python3 for Windows 10.

pytest_reportportal-1.0.1

Example from docs from github.

```
import pytest
import logging

# Import Report Portal logger and handler to the test module.
from pytest_reportportal import RPLogger, RPLogHandler

# Setting up a logging.
logging.setLoggerClass(RPLogger)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create handler for Report Portal.
rp_handler = RPLogHandler()

# Set INFO level for Report Portal handler.
rp_handler.setLevel(logging.INFO)

# Add handler to the logger.
logger.addHandler(rp_handler)


# In this case only INFO messages will be sent to the Report Portal.
def test_one():
    logger.info("Case 1. Step 1")
    x = "this"
    logger.info("x is: %s", x)
    assert 'h' in x

#     Message with an attachment.
    import subprocess
    free_memory = subprocess.check_output("wmic OS get FreePhysicalMemory /Value".split())
    logger.info("Case1. Memory consumption", attachment={"name": "free_memory.txt", "data": free_memory, "mime": "application/octet-stream", }, )

    # This debug message will not be sent to the Report Portal.
    logger.debug("Case1. Debug message")
```

pytest.ini
```
[pytest]
rp_uuid = xxxx-xxxx-xxxx
rp_endpoint = https://rp.epam.com
rp_project = ANATOL_KHMIALEUSKI_PERSONAL
rp_launch = AnyLaunchName
rp_launch_tags = 'PyTest'
rp_launch_description = 'Smoke test'
rp_ignore_tags = 'xfail' 'usefixture'
rp_ignore_errors = True
```

Result

```
Testing started at 3:24 PM ...
D:\VM\Internal_Tools\PyTest&RP\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pycharm\_jb_pytest_runner.py" --path test.py -- -v
Launching py.test with arguments -v test.py in D:\VM\Internal_Tools\PyTest&RP

============================= test session starts =============================
platform win32 -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- D:\VM\Internal_Tools\PyTest&RP\venv\Scripts\python.exe
cachedir: .cache
rootdir: D:\VM\Internal_Tools\PyTest&RP, inifile: pytest.ini
plugins: reportportal-1.0.1
collecting ... collected 1 itemINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\_pytest\main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\_pytest\main.py", line 164, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pluggy\callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pytest_reportportal\listener.py", line 19, in pytest_runtest_protocol
INTERNALERROR>     PyTestService.start_pytest_item(item)
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pytest_reportportal\service.py", line 103, in start_pytest_item
INTERNALERROR>     'tags': self._get_tags(test_item),
INTERNALERROR>   File "D:\VM\Internal_Tools\PyTest&RP\venv\lib\site-packages\pytest_reportportal\service.py", line 118, in _get_tags
INTERNALERROR>     marks = mark_plugin.MarkMapping(keywords)._mymarks
INTERNALERROR> AttributeError: 'MarkMapping' object has no attribute '_mymarks'

======================== no tests ran in 0.03 seconds =========================

Process finished with exit code 0
Empty test suite.
```

**Comment by krasoffski** [comment]
Hi @akhmialevskiy ,

Thank you for issue!

After first look it seems like the root case of changed API of `MarkMapping(object)` class [_pytest/mark.py](https://github.com/pytest-dev/pytest/blob/master/_pytest/mark.py#L200)

Earlier it looked like:

```python
class MarkMapping:
    def __init__(self, keywords):
        mymarks = set()
        for key, value in keywords.items():
            if isinstance(value, MarkInfo) or isinstance(value, MarkDecorator):
                mymarks.add(key)
        self._mymarks = mymarks

    def __getitem__(self, name):
        return name in self._mymarks
```

The issue is accessing __private__ attribute `self._mymarks` which has been renamed.

I will try to fix this today a little bit later.

**Comment by lebovski** [comment]
This problem associated with new version of pytest, you can use pytest <3.3

**Comment by lebovski** [comment]
@krassofski if you want to fix it, please validate pytest version and with depends of version try to get markers

**Comment by krasoffski** [comment]
@lebovski yes, It obvious.  We can support both version (old and new) but with ugly workaround. I am looking for better solution if it is.

**Comment by lebovski** [comment]
@krasoffski thanks, if you need, i can help you)

**Comment by krasoffski** [comment]
@lebovski 
Please take a look at #38 if have a time. I'm not sure you are able to comment, but anyway, let's try.

**Comment by ailjushkin** [comment]
Do we need to maintain both versions?
Someday you will have to upgrade packages. I think if the problem constraints on 3.3 pytest so add new version in requirements.txt so we can say that only latest version supported.

**Comment by lebovski** [comment]
Yes we need, for example, i use allure, and they support not latest version, similar problem can appear with  other plugins.

**Comment by krasoffski** [comment]
Generally, I came up with one more solution for this issue. I will create one more PR after testing.

**Comment by krasoffski** [comment]
Final solution is added. How has a time please take a look or test with Py2/Py3.

**Comment by akhmialevskiy** [comment]
It looks like fixed. Thanks
