### ISSUE TITLE
service stopped when running second time and also AttributeError: 'NoneType' object has no attribute 'post_log'

### ISSUE THREAD

**Issue by tareqalayan** [reportportal/agent-python-pytest#54]
```
platform linux2 -- Python 2.7.14, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
metadata: {'Platform': 'Linux-4.15.6-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven', 'JAVA_HOME': '/usr/java/default', 'WORKSPACE': '/home/talayan/git', 'Plugins': {'jira': '0.3.6', 'art': '0.0.0', 'ordering': '0.5', 'marker-bugzilla': '0.7', 'reportportal': '1.0.1', 'flaky': '3.3.0', 'html': '1.16.0', 'forked': '0.2', 'metadata': '1.5.1'}, 'Python': '2.7.14', 'Packages': {'py': '1.5.2', 'pytest': '3.4.2', 'pluggy': '0.6.0'}}
rootdir: /home/talayan/git/rhevm-art/art/tests/rhevmtests/acceptance/sanity, inifile: /home/talayan/git/rhevm-art/pytest_customization/pytest.cfg
plugins: art-0.0.0, reportportal-1.0.1, ordering-0.5, marker-bugzilla-0.7, jira-0.3.6, forked-0.2, metadata-1.5.1, html-1.16.0, flaky-3.3.0
collected 1 item                                                                                                                                                                             

art/tests/rhevmtests/acceptance/sanity/sanity_test.py Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service_async.py", line 73, in _monitor
    self.handle(record)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service_async.py", line 54, in handle
    handler(record)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service_async.py", line 208, in process_item
    self.terminate(nowait=True)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
Error: Service already stopped.

Traceback (most recent call last):
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/reportportal_client/service.py", line 170, in start_test_item
    r = self.session.post(url=url, json=data)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/urllib3/connectionpool.py", line 396, in _make_request
    httplib_response.length)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/pytest_reportportal/rp_logging.py", line 113, in _log
    return original_func(self, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/home/talayan/git/rhevm-art/.art/lib/python2.7/site-packages/pytest_reportportal/rp_logging.py", line 92, in emit
    return self.py_test_service.post_log(
AttributeError: 'NoneType' object has no attribute 'post_log'
```

**Comment by krasoffski** [comment]
It would be great if you provide steps/tests for reproducing. 

Also the root cause might be related to #24 like missing sync primitives between threads.

**Comment by tareqalayan** [comment]
Yes it is the same as issue mentioned ... 

I am just running a simple one test. 
and my pytest.cfg contains the correct uuid as stated in reportportal profile.

**Comment by krasoffski** [comment]
The mentioned issue #24 just contains a simple case for reproducing. The are a lot of possible cases when this issue might appear.

**Comment by DzmitryHumianiuk** [comment]
close as duplicate in hail of #24
