### ISSUE TITLE
 "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: 

### ISSUE THREAD

**Issue by ravirajdj** [reportportal/agent-python-pytest#63]
Tests were running for few hours, and without any disturbances we can see suddenly testsuite was not reaching report portal.

below is the error screenshots.

'''
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 187, in finish_test_item
    return _get_msg(r)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service.py", line 39, in _get_data
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.233.84.37:8082/api/v1/CONCIERG/item/5b16062c3cdea20001d32ec1
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service_async.py", line 73, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service_async.py", line 54, in handle
    handler(record)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service_async.py", line 208, in process_item
    self.terminate(nowait=True)
  File "/usr/local/lib/python3.6/site-packages/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
reportportal_client.errors.Error: Service already stopped.
 ' ' '

**Comment by evjlobanova** [comment]
@ravirajdj hello, unfortunately now we do not have any python specialist in a team. So feel free to send a pull request, or you can post this issue in our slack chat https://reportportal.slack.com/messages/C9PMAA690, maybe someone from community can help you

**Comment by CorineDMK** [comment]
I have the same problem.

**Comment by NikitaFedoraev** [comment]
Hi,

I had the same problem and in my case, it was due to the changed authorization token. 
Seems that creating a new Project in Reporting Portal changes authorization tokens. 

Try to change rp_uuid in your pytest.ini
 rp_uuid = f8172779-93e0-4353-0000-0000000bb67
