### ISSUE TITLE
Pytest reports 'Service already stopped' and causes incomplete launch be uploaded

### ISSUE THREAD

**Issue by trinhpham** [reportportal/agent-python-pytest#68]
Hello,

I've tried to configured this project 'https://github.com/savoirfairelinux/num2words.git'.
The issue I got after running command 'pytest' is: 
```shellscript
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\lib\site-packages\reportportal_client\service_async.py", line 86, in _monitor
    self.handle(record)
  File "c:\python27\lib\site-packages\reportportal_client\service_async.py", line 54, in handle
    handler(record)
  File "c:\python27\lib\site-packages\reportportal_client\service_async.py", line 208, in process_item
    self.terminate(nowait=True)
  File "c:\python27\lib\site-packages\reportportal_client\service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
Error: Service already stopped.
```

My environment:
- Python 2.7.13 (Windows 10 x64)
- pytest (3.6.2)
- pytest-reportportal (1.0.3)
- reportportal-client (3.1.0)

Screenshots:
![image](https://user-images.githubusercontent.com/9128061/41705131-51c5a09a-7562-11e8-9250-6ce0887869b7.png)
![image](https://user-images.githubusercontent.com/9128061/41705173-6b07e05e-7562-11e8-8eaa-40b659861657.png)

These pacakges are installed via pip.

I think there should be a bug in our library.
Please help review and fix ASAP.

**Comment by evjlobanova** [comment]
@trinhpham hello, unfortunately now we do not have any python specialist in a team. So feel free to send a pull request, or you can post this issue in our slack chat https://reportportal.slack.com/messages/C9PMAA690, maybe someone from community can help you

**Comment by iivanou** [comment]
@trinhpham is that issue still actual?
