### ISSUE TITLE
SSL Errors are hidden

### ISSUE THREAD

**Issue by JMoravec** [reportportal/agent-python-pytest#91]
While working on https://github.com/reportportal/agent-python-pytest/pull/90 it took me awhile to figure out the underlying error (SSL not being verified by requests) as all I saw in the logs was 'Launch not found').

It would be useful if client-Python errors were exposed somehow to the user/pytest.

**Comment by DzmitryHumianiuk** [comment]
@JMoravec would you mind to send us small PR for this?

cc @reportportal/python-contributors

**Comment by JMoravec** [comment]
@DzmitryHumianiuk Sorry, I just noticed this, but I'm not really sure how this would be done, or what an end user might want to see

**Comment by HardNorth** [comment]
Looks OK-ish to me:
```
agent-python-pytest/venv/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py --path tests -- -m "not command_skip" --reportportal
Testing started at 2:17 PM ...
Launching pytest with arguments -m not command_skip --reportportal tests --no-header --no-summary -q in examples-python/pytest

HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/project/default_personal (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
Traceback (most recent call last):
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "agent-python-pytest/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/project/default_personal (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "agent-python-pytest/pytest_reportportal/plugin.py", line 39, in check_connection
    verify=aconf.rp_verify_ssl)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "agent-python-pytest/venv/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/project/default_personal (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
```
